name: te-simulation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - biopython=1.79
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pandas=1.4.2
  - r-base=4.1.3
  - r-ggplot2=3.3.5
  - r-reshape2=1.4.4
  - r-dplyr=1.0.8
  - pip=22.0.4
  - pip:
    - pyfaidx==0.6.4
